givenname = input("Given name: ")
familyname = input("Family name:")
address = input("Street address:")
postalcode = input("City and postal code:")
print(givenname,familyname)
print(address)
print(postalcode)